###get the day's movies
GET http://localhost:3000/movies

###create new movie
POST http://localhost:3000/movies
Content-Type: application/json

{
  "movie_title": "test",
  "runtime": 119,
  "theater_number": 1,
  "time_slot": "April 2 2022, 10:30 AM"
}

###sell tickets
POST http://localhost:3000/tickets
Content-Type: application/json

{
  "movie_id": 4,
  "tickets_sold": 60
}

###create report
POST http://localhost:3000/reports

###update movie
PATCH http://localhost:3000/movies/4
Content-Type: application/json

{
  "movie_title": "patch test",
  "runtime": 300,
  "time_slot": "April 3rd, 2022, 12PM"
}

###delete movie
DELETE http://localhost:3000/movies/8